services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:password123@db:5432/db123
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    command: npm run dev
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - ./src/database/migrations/latest.sql:/docker-entrypoint-initdb.d/01-latest.sql
      - ./src/database/seeds/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db123
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
